version: '3.1'
services:
  website:
    image: php:apache
    depends_on:
      - API
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - student_network
    environment:
      - USERNAME=toto
      - PASSWORD=python
  API:
    image: api
    ports:
      - "8000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - student_network
networks:
  student_network:
